version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_app_local
    volumes:
      - postgres-data:/var/lib/todo-app/postgresql/data

volumes:
  postgres-data: